### ISSUE TITLE
Adopt granary-model-dashboard

### ISSUE THREAD

**Issue by jisantuc** [raster-foundry/granary#366]
A while ago for fun times I made a [dashboard](https://github.com/jisantuc/granary-model-dashboard/) for Granary models in Elm. Now it turns out we need one :fearful: so we're going to assimilate it.

![](https://media.giphy.com/media/V6J9e90If8YyA/source.gif)

That involves several steps:

- [x] the Granary README should include information for getting set up to do development of the dashboard (how to get the correct Elm extension for VSCode, how to get elm-format, first time app startup... basically all the tacit knowledge)
- [x] the static assets for the dashboard should be served from the Granary server
- [x] the dashboard should be built as part of the Granary CI process (probably this can just live in `scripts/update` or a more targeted script that can be called separately but is also card as part of `scripts/update`)
- [x] the static assets for the dashboard should be bundled in the correct place into the published container
- ~the location of the Granary API should be [parameterized](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#using-custom-environment-variables) like we do for Groundwork and different RF APIs~ not necessary, since we're serving from the same host :tada:

**Comment by notthatbreezy** [comment]
[Franklin](https://github.com/azavea/franklin/blob/master/application/src/main/scala/com/azavea/franklin/api/services/StaticService.scala) has an example static service that serves files from the `assets/` directory inside resources -- I think we can do something similar here
