### ISSUE TITLE
Tasks page

### ISSUE THREAD

**Issue by jisantuc** [raster-foundry/granary#367]
Currently the task list shows names and AWS configuration.

![image](https://user-images.githubusercontent.com/5702984/89463390-14758380-d72c-11ea-8a31-fe7a102a8d3e.png)

Instead, the model page should:

- [x] have a dropdown for the available tasks (while they're technically paginated, we're not going to worry about the "more tasks than the first page holds" problem right now)
- [x] on task selection, render a form using the task's validator
- [x] allow submitting a new execution for the task when all the form data is correct
- [x] on successful submission, navigate to the executions page with the executions filtered to those for this task

The form should understand the magic `TASK_GRID` key and allow a file input so people don't have to copy and paste potentially large geojson files.

For consistent styles and better defaults than my super fancy bespoke styling, use one of [`elm-ui-framework`](https://package.elm-lang.org/packages/Orasund/elm-ui-framework/latest/) or [`style-framework`](https://package.elm-lang.org/packages/lucamug/style-framework/latest/)

**Comment by jcahail** [comment]
Includes ELM orientation.
